join/api/urls.py
from django.urls import path, include
from rest_framework.authtoken import views

from api.api_view import (APIPost, APIPostDetail,
                       APIGenericPostList, APIGenericPostDetail, FollowViewSet,
                       PostViewSet, GroupViewSet, CommentViewSet)
from rest_framework.routers import DefaultRouter


app_name = 'api'  # у прилож. должно быть имя, далее исп его в namespace

# создаём роутер
router = DefaultRouter()
# регистрируем созданный ViewSet
#api/v1/posts/ (GET, POST): получаем список всех постов или создаём новый пост
#api/v1/posts/{post_id}/ (GET, PUT, PATCH, DELETE): получаем, редактируем или удаляем пост по id
router.register(r'posts', PostViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'^posts/(?P<post_id>\d+)/comments', CommentViewSet, basename='comment')
router.register(r'follow', FollowViewSet, basename='follow')



urlpatterns = [
    # получение простого токена по логину и паролю
    #path('api/v1/api-token-auth/', views.obtain_auth_token),
    # path('api/v1/posts/<int:pk>', APIGenericPostDetail.as_view(), name='api_post_detail'),
    # path('api/v1/posts/', APIGenericPostList.as_view(), name='api_posts'),
    # получение токена JWT
    # Djoser создаст набор необходимых эндпоинтов.
    # базовые, для управления пользователями в Django:
    path('auth/', include('djoser.urls')),
    # JWT-эндпоинты, для управления JWT-токенами:
    path('auth/', include('djoser.urls.jwt')),
    path('', include(router.urls))
]

join/join/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
# подключаем плагин для генерации документации
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path(
        'group/<slug:slug>/',
        include('posts.urls', namespace='posts')
        ),
    path('group/', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    #path("__debug__/", include("debug_toolbar.urls"))
    path('api/v1/', include('api.urls', namespace='api')),
    # Генерация OpenAPI схемы
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Swagger UI
    path('api/v1/docs/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    # Redoc
    path('api/v1/docs/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:  # если режим разработки True
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # в режиме DEBUG=True брать картинки из директории, указанной в MEDIA_ROOT
    # по имени, через префикс MEDIA_URL.

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

join/users/urls.py
from django.contrib.auth.views import (LogoutView, LoginView,
                                       PasswordResetView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path
from . import views


app_name = 'users'  # у прилож. должно быть имя, далее исп его в namespace

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    # Прямо в описании обработчика укажем шаблон,
    # который должен применяться для отображения возвращаемой страницы.
    # Да, во view-классах так можно! Как их не полюбить.
    # Теперь при обработке запроса auth/logout/ будет использоваться
    # контент, генерируемый LogoutView, а шаблон будет взят
    # из папки templates/users/logged_out.html
    path('signup/', views.SignUp.as_view(), name='signup'),
    # Полный адрес страницы регистрации - auth/signup/,
    # но префикс auth/ обрабатывется в головном urls.py
    path('login/',
         LoginView.as_view(template_name='users/login.html'), name='login'),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

join/posts/models.py
from django.db import models
# Для работы с моделями импортируется модуль models
from django.contrib.auth import get_user_model
# Для создания поля со ссылкой на модель User импортируется и эта модель:
# она встроена в Django и отвечает за управление пользователями.
from pytils.translit import slugify
from posts.validators import validate_not_empty


User = get_user_model()


class Tag(models.Model):
    """Хэштэги к постам.

    Связаны с постами отношением «многие-ко-многим».
    При запросе постов должна возвращаться информация о всех
    связанных с конкретным постом хештегах, а при добавлении
    или обновлении поста нужно обеспечить возможность
    передавать названия хештегов списком прямо в теле запроса.
    Без указания хештегов пост через API тоже должен создаваться.
    """
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Читаемая ссылка')
    description = models.TextField(verbose_name='Описание')

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    # Расширение встроенного метода save(): если поле slug не заполнено -
    # транслитерировать в латиницу содержимое поля title и
    # обрезать до ста знаков
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)[:100]
        super().save(*args, **kwargs)


class Post(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name='Название поста',
        validators=[validate_not_empty],
        help_text='Введите название поста'
        )
    anons = models.CharField(max_length=250, blank=True)
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста',
        validators=[validate_not_empty],
        )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
        )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
        )
    # в объекте пользователя появилось поле posts,
    # в котором хранятся ссылки на все посты этого автора.
    # И теперь можно получить список постов автора,
    # обратившись к его свойству posts
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    # Аргумент upload_to указывает директорию,
    # в которую будут загружаться пользовательские файлы.
    # Путь в параметре upload_to указывается относительно адреса,
    # указанного в settings.py в MEDIA_ROOT: в нём устанавливают полный путь
    # к директории, куда будут загружаться файлы пользователей: обычно её
    # называют media/.
    # таким образом картинки, прикреплённые к постам, будут сохраняться
    # в директории media/posts.

    # Связь будет описана через вспомогательную модель TagPost
    # Связываем модель Post с моделью Tag через таблицу связи TagPost
    tag = models.ManyToManyField(Tag, through='TagPost')

    def __str__(self) -> str:
        return self.text[:30]

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date']


# В этой модели будут связаны id поста и id его тэгов
# вспомогательная таблица для связи "многие-ко-многим"
class TagPost(models.Model):
    """Связывает посты и тэги.

    Каждый тэг может принадлежать многим постам, так же
    как и каждый пост может обладать многими тэгами.
    Связь "многие-ко-многим".
    """

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post} {self.tag}'


class Comment(models.Model):
    """Создание комментария к посту.

    Комментировать может только зарегистрированный пользователь.
    """
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Напишите комментарий к посту'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Имя автора комментария'
    )
    text = models.TextField(
        max_length=500,
        verbose_name='Комментарий',
        validators=[validate_not_empty]
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата'
    )

    def __str__(self):
        return self.text[:30]

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created']


class Follow(models.Model):
    """Система подписки на авторов."""
    # пользователь, который подписывается
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Пользователь, который подписывается на автора'
    )
    # пользователь, на которого подписываются
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Автор, на которого подписываются'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ['id']
        # чтобы не допустить подписку на одного и того же автора дважды
        # Такую же проверку нужно реализовать и на уровне сериализатора.
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follower_author'
            )
        ]

    def __str__(self):
        return f'{self.user} подписан на {self.author}'


class Contact(models.Model):
    """Обратная связь с администратором сайта.

    Позволяет написать сообщение администратору.
    """
    name = models.CharField(max_length=100, validators=[validate_not_empty])
    email = models.EmailField()
    subject = models.CharField(max_length=100, validators=[validate_not_empty])
    body = models.TextField(max_length=1000)
    is_answered = models.BooleanField(default=False)

join/users/models.py
from django.db import models

# Create your models here.

join/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()
# Функция get_user_model() обращается именно к той модели,
# которая зарегистрирована в качестве основной модели пользователей
# в конфиге проекта.


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        #  наследуется класс Meta, вложенный в класс UserCreationForm
        # укажем модель, с которой связана создаваемая форма
        model = User
        # тк User = get_user_model(), то по сути model = get_user_model()
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

join/users/views.py
from django.shortcuts import render
# Импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView
# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy
# импортируем созданный нами класс формы CreationForm из users/forms.py
from .forms import CreationForm


class SignUp(CreateView):
    # Форма будет работать с созданным нами классом формы CreationForm
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную
    success_url = reverse_lazy('posts:index')
    # posts - пространство имён namespace
    # index - name из path
    template_name = 'users/signup.html'
    # имя шаблона, куда будет передана переменная form с объектом HTML-формы

join/users/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block main_info %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из учётной записи. Ждём Вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

join/users/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block main_info %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }} {# escape исключает HTML-символы из значения #}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
                {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
              </div>
            </div> {# div class="form-group row my-3" #}
          {% endfor %} {# for field in form #}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                Забыли пароль?
            </a>
          </div>
          </form> {# form method="post" #}
        </div> {# card-body #}
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

join/users/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён успешно{% endblock %}
{% block main_info %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body"> 
            <p>Пароль изменён успешно</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

join/users/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block main_info %}
{% load user_filters %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'users:password_change_form' %}">
              <input type="hidden" name="csrfmiddlewaretoken" value="">
                {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_old_password">
                  Старый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                  </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Изменить пароль
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

join/users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block main_info %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="{% url 'users:login' %}">войти</a>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %}

join/users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block main_info %}
{% load user_filters %}
{% if validlink %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Введите новый пароль
        </div>
        <div class="card-body">
          <form method="post"> <!-- здесь не нужен action, т к аргументы будут меняться каждый раз генерируясь заново --> 
            <input type="hidden" name="csrfmiddlewaretoken" value="">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль        
                  <span class="required text-danger">*</span>        
                </label>    
                <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul>
                    <li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li>
                    <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                    <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                    <li>Ваш пароль не может состоять только из цифр.</li>
                  </ul>
                </small>      
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля        
                  <span class="required text-danger">*</span>        
                </label>    
                <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Назначить новый пароль
                </button>
              </div>
          </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
<!-- если использована неправильная ссылка -->
{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Ошибка
      </div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->  
{% endif %}
{% endblock %}

join/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block main_info %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body"> 
          <p>
            Проверьте свою почту, вам должно прийти письмо со
             ссылкой для восстановления пароля
          </p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

join/users/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Повторная установка пароля{% endblock %}
{% block main_info %}
<div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body"> 
            <form method="post" action="{% url 'users:password_reset_form' %}">
              <input type="hidden" name="csrfmiddlewaretoken" value="">
                {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>    
                <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>  
  </div>
{% endblock %}

join/users/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block main_info %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Зарегистрироваться
      </div>

      <div class="card-body">
      {% load user_filters %}  {# загружаем созданные фильтры #}
        {# Этот блок будет показан, если в форме есть ошибки #}
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}            
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}

        <form method="post" action="{% url 'users:signup' %}">
          {% csrf_token %}

          {# Выводим поля в цикле, по отдельности #}
          {% for field in form %}
          <div class="form-group row my-3 p-3">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
            </label>
            {# К полю ввода добавляем атрибут class #}
            {{ field|addclass:'form-control' }}
            {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
            {% endif %}
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Зарегистрироваться
            </button>
          </div>
        </form>

      </div> <!--card-body-->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 