join/api/urls.py
from django.urls import path, include
from rest_framework.authtoken import views

from api.api_view import (APIPost, APIPostDetail,
                       APIGenericPostList, APIGenericPostDetail, FollowViewSet,
                       PostViewSet, GroupViewSet, CommentViewSet)
from rest_framework.routers import DefaultRouter


app_name = 'api'  # у прилож. должно быть имя, далее исп его в namespace

# создаём роутер
router = DefaultRouter()
# регистрируем созданный ViewSet
#api/v1/posts/ (GET, POST): получаем список всех постов или создаём новый пост
#api/v1/posts/{post_id}/ (GET, PUT, PATCH, DELETE): получаем, редактируем или удаляем пост по id
router.register(r'posts', PostViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'^posts/(?P<post_id>\d+)/comments', CommentViewSet, basename='comment')
router.register(r'follow', FollowViewSet, basename='follow')



urlpatterns = [
    # получение простого токена по логину и паролю
    #path('api/v1/api-token-auth/', views.obtain_auth_token),
    # path('api/v1/posts/<int:pk>', APIGenericPostDetail.as_view(), name='api_post_detail'),
    # path('api/v1/posts/', APIGenericPostList.as_view(), name='api_posts'),
    # получение токена JWT
    # Djoser создаст набор необходимых эндпоинтов.
    # базовые, для управления пользователями в Django:
    path('auth/', include('djoser.urls')),
    # JWT-эндпоинты, для управления JWT-токенами:
    path('auth/', include('djoser.urls.jwt')),
    path('', include(router.urls))
]

join/join/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
# подключаем плагин для генерации документации
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path(
        'group/<slug:slug>/',
        include('posts.urls', namespace='posts')
        ),
    path('group/', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    #path("__debug__/", include("debug_toolbar.urls"))
    path('api/v1/', include('api.urls', namespace='api')),
    # Генерация OpenAPI схемы
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Swagger UI
    path('api/v1/docs/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    # Redoc
    path('api/v1/docs/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:  # если режим разработки True
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # в режиме DEBUG=True брать картинки из директории, указанной в MEDIA_ROOT
    # по имени, через префикс MEDIA_URL.

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

join/posts/urls.py
from django.urls import path, include
from . import views
from api.api_view import (APIPost, APIPostDetail,
                       APIGenericPostList, APIGenericPostDetail,
                       PostViewSet, GroupViewSet, CommentViewSet)
from rest_framework.routers import DefaultRouter


app_name = 'posts'  # переменная namespase
# создаём роутер
#router = DefaultRouter()
# регистрируем созданный ViewSet
#api/v1/posts/ (GET, POST): получаем список всех постов или создаём новый пост
#api/v1/posts/{post_id}/ (GET, PUT, PATCH, DELETE): получаем, редактируем или удаляем пост по id
#router.register(r'posts', PostViewSet)
#router.register(r'groups', GroupViewSet)
#router.register(r'^posts/(?P<post_id>\d+)/comments', CommentViewSet, basename='comment')


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('group/', views.all_groups, name='all_groups'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('profile/<str:username>/', views.profile, name='profile'),
    # Django ожидает строковое значение и преобразует его
    # в представление — переменную username.
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Django ожидает целочисленное значение и преобразует его
    # в представление — переменную post_id.
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path('search/', views.search_view, name='search'),  # Добавляешь путь для поиска
    # path('api/v1/posts/<int:pk>', APIGenericPostDetail.as_view(), name='api_post_detail'),
    # path('api/v1/posts/', APIGenericPostList.as_view(), name='api_posts'),
    #path('api/v1/', include(router.urls))
]

join/posts/models.py
from django.db import models
# Для работы с моделями импортируется модуль models
from django.contrib.auth import get_user_model
# Для создания поля со ссылкой на модель User импортируется и эта модель:
# она встроена в Django и отвечает за управление пользователями.
from pytils.translit import slugify
from posts.validators import validate_not_empty


User = get_user_model()


class Tag(models.Model):
    """Хэштэги к постам.

    Связаны с постами отношением «многие-ко-многим».
    При запросе постов должна возвращаться информация о всех
    связанных с конкретным постом хештегах, а при добавлении
    или обновлении поста нужно обеспечить возможность
    передавать названия хештегов списком прямо в теле запроса.
    Без указания хештегов пост через API тоже должен создаваться.
    """
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Читаемая ссылка')
    description = models.TextField(verbose_name='Описание')

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    # Расширение встроенного метода save(): если поле slug не заполнено -
    # транслитерировать в латиницу содержимое поля title и
    # обрезать до ста знаков
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)[:100]
        super().save(*args, **kwargs)


class Post(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name='Название поста',
        validators=[validate_not_empty],
        help_text='Введите название поста'
        )
    anons = models.CharField(max_length=250, blank=True)
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста',
        validators=[validate_not_empty],
        )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
        )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
        )
    # в объекте пользователя появилось поле posts,
    # в котором хранятся ссылки на все посты этого автора.
    # И теперь можно получить список постов автора,
    # обратившись к его свойству posts
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    # Аргумент upload_to указывает директорию,
    # в которую будут загружаться пользовательские файлы.
    # Путь в параметре upload_to указывается относительно адреса,
    # указанного в settings.py в MEDIA_ROOT: в нём устанавливают полный путь
    # к директории, куда будут загружаться файлы пользователей: обычно её
    # называют media/.
    # таким образом картинки, прикреплённые к постам, будут сохраняться
    # в директории media/posts.

    # Связь будет описана через вспомогательную модель TagPost
    # Связываем модель Post с моделью Tag через таблицу связи TagPost
    tag = models.ManyToManyField(Tag, through='TagPost')

    def __str__(self) -> str:
        return self.text[:30]

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date']


# В этой модели будут связаны id поста и id его тэгов
# вспомогательная таблица для связи "многие-ко-многим"
class TagPost(models.Model):
    """Связывает посты и тэги.

    Каждый тэг может принадлежать многим постам, так же
    как и каждый пост может обладать многими тэгами.
    Связь "многие-ко-многим".
    """

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post} {self.tag}'


class Comment(models.Model):
    """Создание комментария к посту.

    Комментировать может только зарегистрированный пользователь.
    """
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Напишите комментарий к посту'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Имя автора комментария'
    )
    text = models.TextField(
        max_length=500,
        verbose_name='Комментарий',
        validators=[validate_not_empty]
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата'
    )

    def __str__(self):
        return self.text[:30]

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created']


class Follow(models.Model):
    """Система подписки на авторов."""
    # пользователь, который подписывается
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Пользователь, который подписывается на автора'
    )
    # пользователь, на которого подписываются
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Автор, на которого подписываются'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ['id']
        # чтобы не допустить подписку на одного и того же автора дважды
        # Такую же проверку нужно реализовать и на уровне сериализатора.
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follower_author'
            )
        ]

    def __str__(self):
        return f'{self.user} подписан на {self.author}'


class Contact(models.Model):
    """Обратная связь с администратором сайта.

    Позволяет написать сообщение администратору.
    """
    name = models.CharField(max_length=100, validators=[validate_not_empty])
    email = models.EmailField()
    subject = models.CharField(max_length=100, validators=[validate_not_empty])
    body = models.TextField(max_length=1000)
    is_answered = models.BooleanField(default=False)

join/posts/forms.py
from django import forms
# Импортируем модуль forms, из него возьмём класс ModelForm
from .models import Contact, Post, Comment, User, Group
# Из этой же директории из файда models.py импортируем класс Contact



# Создаём класс формы на основе модели Post
class PostForm(forms.ModelForm):
    """Форма создания/редактирования поста."""
    # эта форма будет работать с моделью Post
    class Meta:
        model = Post
        # Здесь перечислим те поля модели, которые будут отображены
        # в вэб форме
        fields = ('title', 'anons', 'text', 'group', 'image')
        # если хотим переопределить поля label, пишем так
        labels = {
            'text': 'текст',
            'title': 'заголовок',
            'anons': 'анонс',
            'group': 'группа',
            'image': 'изображение'
        }


class CommentForm(forms.ModelForm):
    """Форма создания комментария к посту."""
    # эта форма будет работать с моделью Comment
    class Meta:
        model = Comment
        fields = ('text',)


class ContactForm(forms.ModelForm):
    # эта форма будет работать с моделью Contact
    class Meta:
        model = Contact
        # Здесь перечислим те поля модели, которые будут отображены
        # в вэб форме
        fields = ('name', 'email', 'subject', 'body',)
        # в основном коде django с моделях auth/forms.py
        # поля перечисляют в круглых скобках

join/posts/templates/posts/all_groups.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block main_info %}
    <div class="container py-5">
      <h1 class="display-4 text-center text-primary">Список всех групп</h1>
      <p class="lead text-center">{{ inf_groups|safe }}</p>
    </div>
{% endblock %}

join/posts/templates/posts/create_post copy.html
{% extends "base.html" %}
{% load uglify %}

{% block title %}
  {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %}
{% endblock %}

{% block main_info %}

<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %} Редактировать пост {% else %} Создать новый пост {% endif %}
          </div>
          <!--Проверка на ошибки-->
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ field.label }}: {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
          {% endif %}
          <div class="card-body">        
            <form method="post" action="{% url 'posts:post_create' %}">
            {% csrf_token %}    
              <input type="hidden" name="csrfmiddlewaretoken" value="">
              <div class="form-group row my-3 p-3">
                <label for="id_title">
                  Название поста                  
                  <span class="required text-danger">*</span>                  
                </label>
                <input name="text" class="form-control" required id="id_title">
                </input>               
                <small id="id_title-help" class="form-text text-muted">
                  Название нового поста
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_anons">
                  Анонс                                    
                </label>
                <textarea name="text" class="form-control" required id="id_anons">
                </textarea>               
                <small id="id_anons-help" class="form-text text-muted">
                  Анонс нового поста
                </small>
              </div>                                
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста                  
                  <span class="required text-danger">*</span>                  
                </label>
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                </textarea>                
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>                  
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Group                  
                </label>
                <select name="group" class="form-control" id="id_group">
                  <option value="" selected>---------</option>
                  <option value="1">Группа: Лев Толстой – зеркало русской революции</option>
                </select>
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

join/posts/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ title }}{% endblock %}

{% block main_info %}
  <div class="container py-2">
    <h3>{{ title }}</h3>
  </div>
  <div class="container py-2">
    <!-- Виджет переключения лент -->
    {% include "includes/switcher.html" %}
  </div>
  <div class="container py-5">
    {% for post in page_obj %}
    <ul>
      <li class="list-group-item">
        Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.username }}</a>
      </li>
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}
      <li class="list-group-item">
        Все записи группы: <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
      </li>
      {% endif %}
    </ul>
    <h4><b>{{ post.title }}</b></h4>
    {% if post.anons %}
      <i>{{ post.anons }}</i>
    {% endif %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|truncatewords:30 }}</p>
    <a href="{% url 'posts:post_detail' post_id=post.id %}">подробная информация</a>
    {% if not forloop.last %}
      <hr>
    {% endif %}
    {% endfor %}
  </div>

  {% include "includes/paginator.html" %}
{% endblock %}

join/posts/templates/posts/group_posts.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
  Страница группы {{ group.title }}
{% endblock %}

{% block main_info %}
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
       <h2>{{ group.title }}</h2>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
      <p>{{ group.description|linebreaks }}</p>
      {% for post in page_obj %}
        <ul>
            <li class="list-group-item">
                Автор:
                <a href="{% url "posts:profile" post.author.username %}">{{ post.author.username }}</a>
            </li>
            <li class="list-group-item">
                Дата публикации: {{ post.pub_date|date:'d E Y' }}
            </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <h3>{{ post.title}}</h3>
        <h5>{{ post.anons}}</h5>
        <p>{{ post.text|linebreaks|truncatewords:30 }}</p>
        <p>
          <a href="{% url "posts:post_detail" post.pk %}">Подробная информация</a>
        </p>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </div>
  </div>
</div>

    {% include "includes/paginator.html" %}

{% endblock %}

join/posts/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% load uglify %}

{% block title %}{{ title }}{% endblock %}

{% block main_info %}
  <div class="container py-2">
    <h3>{{ title }}</h3>
  </div>
  <div class="container">
    <h1>Поиск по записям</h1>

    <div class="card">
      <div class="card-body">
        <form class="form-inline" action="/search/">
          <div class="form-row">
            <input name="q" class="form-control form-control-lg" type="search"
            placeholder="Поиск" {% if keyword %} value="{{ keyword }}"{% endif %}>
            <button class="btn" type="submit">Найти</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="container">
    {% for post in posts %}
    <strong>
      Автор: {{ post.author.username }},
      Дата публикации: {{ post.pub_date|date:"d M Y" }},
      Группа: {{ post.group.title }}
    </strong>
    <h4>{{ post.title }}</h4>
    <h5><i>{{ post.anons }}</i></h5>
    <p>{{ post.text|linebreaks }}</p>
    {% endfor %}

  </div>

  {% include "includes/switcher.html" %}

  <div class="container py-5">
    {% for post in page_obj %}
    <ul>
      <li class="list-group-item">
        Автор:<a href="{% url 'posts:profile' post.author.username %}">{{ post.author.username }}</a>
      </li>
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}
      <li class="list-group-item"> Все записи группы:
        <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
      </li>
      <h4><b>{{ post.title }}</b></h4>
      {% if post.anons %}
        <i>{{ post.anons }}</i>
      {% endif %}
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|truncatewords:30 }}</p>
      <a href="{% url 'posts:post_detail' post_id=post.id %}">подробная информация</a>
      {% endif %}
    </ul>
    {% if not forloop.last %}
        <hr>
    {% endif %}
    {% endfor %}
  </div>

  {% include "includes/paginator.html" %}
{% endblock %}

join/posts/templates/posts/post_create.html
{% extends "base.html" %}
{% load uglify %}

{% block title %}
  {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %}
{% endblock %}

{% block main_info %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %} Редактировать пост {% else %} Создать новый пост {% endif %}
          </div>
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ field.label }}: {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
          {% endif %}
          <div class="card-body">
            <form method="post" action="{% if post %}{% url 'posts:post_edit' post.id %}{% else %}{% url 'posts:post_create' %}{% endif %}" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

join/posts/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}

{% block main_info %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Дата публикации: {{ post.pub_date|date:'d E Y' }}</li>
      {% if post.group %}
      <li class="list-group-item">
        Группа:
        <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
      </li>
      {% endif %}
      <li class="list-group-item">
        Автор:
        <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.username }}</a>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: <span>{{ posts_count }}</span>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <div>
      <h4>{{ post.anons }}</h4>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>
      {% if user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">Редактировать запись</a>
      {% endif %}
    </div>
  </article>
</div>

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ comment_form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' username=comment.author.username %}">{{ comment.author.username }}</a>
      </h5>
      <p>{{ comment.text }}</p>
    </div>
  </div>
{% endfor %}

{% endblock %}

join/posts/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}

{% block main_info %}

    <div class="container py-5">
      <div class="mb-5">
        <h1>Все посты пользователя {{ author.username }} </h1>
        <h3>Имя пользователя: {{ author.get_full_name }} </h3>
        <h3>Всего постов: {{ posts_author.count }} </h3>
        <!--Если пользователь автор профиля, ему кнопки вообще не показывать-->
        {% if author != request.user %}
          <!--Если пользователь уже подписан на автора - показывать "Отписаться"-->
          {% if following %} <!--True-->
            <a class="btn btn-lg btn-light"
              href={% url "posts:profile_unfollow" username=author.username %}
              role="button"
            >
            Отписаться
            </a>
          <!--Если не подписан на автора - показывать "Подписаться"-->
          {% else %}  <!--False-->
            <a class="btn btn-lg btn-light"
              href={% url "posts:profile_follow" username=author.username %}
              role="button"
            >
            Подписаться
            </a>
          {% endif %}
        {% endif %}
      </div>

      {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ author.username }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:'d E Y' }}
            </li>
          </ul>
          <h4>
              {{ post.title|linebreaksbr }}
          </h4>
          <p>
            {% if post.anons %}  <!--если есть анонс-->
              {{ post.anons|linebreaksbr }}
            {% endif %}
          </p>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text|truncatewords:30 }}
          </p>
          <ul>
            {% if post.group %}  <!--если у поста есть группа -->
              <li>
                <a href="{% url "posts:group_list" post.group.slug %}">{{ post.group }}</a>
                <!-- в этом посте берём значение группы в человекочитаемой форме -->
              </li>
            {% endif %}
            <li>
              <a href="{% url "posts:post_detail" post.pk %}">Подробная информация</a>
              <!-- posts - namespace, post_detail - name from path -->
              <!-- в этом посте берём значение pk -->
            </li>
          </ul>

          {% if not forloop.last %}<hr>{% endif %}
          <!--если это не последняя итерация, ставим горизонтальную черту-->
        </article>
      {% endfor %}

      <hr>
      <!-- Остальные посты. после последнего нет черты -->
      <!-- Здесь подключён паджинатор -->
      {% include "includes/paginator.html" %}
    </div>

{% endblock %}

join/posts/templates/posts/search_results.html
{% extends "base.html" %}

{% block title %}Результаты поиска{% endblock %}

{% block main_info %}
<div class="container">
    <h1>Результаты поиска для "{{ keyword }}"</h1>

    {% if posts %}
        <ul>
            {% for post in posts %}
                <li>
                    <a href="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Записи не найдены.</p>
    {% endif %}
</div>
{% endblock %}